# Hydra: functional computer hardware description language

Hydra is a functional computer hardware description language for
specifying the structure and behavior of digital circuits. It supports
several levels of abstraction, including logic gates, register
transfer level, datapath and control, and processors. There are tools
for simulating circuits, generating netlists, and emulating
instruction set architectures. It is an embedded domain specific
language implemented using Haskell.

This is free and open source software released under the GPL-3
license.

*** Documentation

There are several forms of documentation.
- The user guide, available in docs/HydraUserGuide, gives a tutorial
  explanation of how to use the software.
- The API reference is in the dist-newstyle directory.  The exact
  location depends on software versions, but looks something like
  this:

#+BEGIN_EXAMPLE
\Hydra\dist-newstyle\build\x86_64-windows\ghc-9.2.3\hydra-3.4.15\doc\html\hydra\index.html
#+END_EXAMPLE

*** Installation

**** Haskell

Hydra requires the ghc toolset for Haskell, including ghc and cabal.
Haskell installers for Macintosh, Windows, and Linux are available
at https://www.haskell.org/ghcup/

For Windows, an alternative approach is to use chocolatey; see
https://hub.zhox.com/posts/introducing-haskell-dev/
If you have chocolatey installed, you can use it to install Haskell
easily.  Run in Windows PowerShell with administrator priveleges:

#+BEGIN_EXAMPLE
choco install ghc --force -y
choco install cabal --force -y
#+END_EXAMPLE

If you have a previous installation, the following might work:
#+BEGIN_EXAMPLE
choco upgrade ghc cabal -y
#+END_EXAMPLE

- force shouldn't be necessary but seems to be needed if installing
  after a failed installation attempt
- -y is necessary; this tells choco to answer with y automatically
  when it needs permission to do something.  Without the -y, it
  doesn't actually ask permission, and the whole installation fails

/Test the Haskell tools/

#+BEGIN_EXAMPLE
$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 9.0.1
$ cabal --version
cabal-install version 3.4.0.0
compiled using version 3.4.0.0 of the Cabal library
#+END_EXAMPLE

**** Install Hydra

- Download the source from https://github.com/jtod/Hydra
- Unzip the source file and put it anywhere in your workspace.
  - On Linux: tar -xzf Hydra-i.j.k.tgz
  - On Windows use zip, 7zip or tar
- In you shell, go to the source directory and enter

#+BEGIN_EXAMPLE
cabal install --lib
cabal haddock
#+END_EXAMPLE

/Test the installation/

In your shell, go to Hydra/examples/adder and enter

#+BEGIN_EXAMPLE
ghc -e main Add4Run
#+END_EXAMPLE

This should produce several lines of simulation output showing inputs
to the adder circuit and the corresponding outputs.

/Troubleshooting/

On Windows: If cabal fails, delete this directory and try again:
#+BEGIN_EXAMPLE
C:\Users\yourname\AppData\Roaming\cabal\store
#+END_EXAMPLE

Additional useful commands; see the ghc User Guide:
#+BEGIN_EXAMPLE
ghc-pkg list
ghc-pkg unregister hydra-i.j.k
#+END_EXAMPLE

** About Hydra

- Author: John T. O'Donnell, School of Computing Science, University
  of Glasgow
- Copyright (c) 2022 John T. O'Donnell
- License: This software is free and open source, using the GPL-3
  license.  See LICENSE.txt.
- Version: see Hydra.cabal
- Hydra web page: https://github.com/jtod/Hydra
- Author's web page: https://jtod.github.io/index.html
